title: Ishu Jaswani # your name (or website title) here
logo: "/images/ID.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a synergic individual who has a strong work ethic. A CFA Level 2 candidate with a post graduate diploma in Economics and specialization in Data Analytics.
  <br><br>
  After engeenering multiple academic projects, my interests in this industry peaked and in order to hone my programming and analytical skills I undertook these three projects.
  <br><br>
  <br><br>
  
  <a href="https://www.linkedin.com/in/ishu-jaswani-354566160">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
